{{ config( 
  materialized = 'ephemeral', 
  tags=['Wind_Speed']
    ) 
}} 
WITH WIND_SPEED_AVG AS (
    SELECT INPUT_DATE, PROVINCE_CODE, CITY_CODE, WIND_DIRECTION_AVG, COUNT(*) COUNT_ROW
    FROM {{ source('Raw', 'Weather_Data') }}
    GROUP BY INPUT_DATE, PROVINCE_CODE, CITY_CODE, WIND_DIRECTION_AVG
), WIND_SPEED_MAX AS (
    SELECT INPUT_DATE, PROVINCE_CODE, CITY_CODE, WIND_DIRECTION_MAX, COUNT(*) COUNT_ROW
    FROM {{ source('Raw', 'Weather_Data') }}
    GROUP BY INPUT_DATE, PROVINCE_CODE, CITY_CODE, WIND_DIRECTION_MAX
), SORT_WIND_SPEED_AVG AS(
    SELECT 
        INPUT_DATE, PROVINCE_CODE, CITY_CODE, b.DIRECTION_EN WIND_DIRECTION_AVG, COUNT_ROW,
        ROW_NUMBER() OVER(PARTITION BY INPUT_DATE, CITY_CODE ORDER BY COUNT_ROW DESC) SORT_ROW
    FROM WIND_SPEED_AVG a
    LEFT JOIN {{ ref('Direction') }} b
), SORT_WIND_SPEED_MAX AS(
    SELECT 
        INPUT_DATE, PROVINCE_CODE, CITY_CODE, b.DIRECTION_EN WIND_DIRECTION_MAX, COUNT_ROW,
        ROW_NUMBER() OVER(PARTITION BY INPUT_DATE, CITY_CODE ORDER BY COUNT_ROW DESC) SORT_ROW
    FROM WIND_SPEED_MAX a
    LEFT JOIN {{ ref('Direction') }} b
)
SELECT 
    a.INPUT_DATE, a.PROVINCE_CODE, a.CITY_CODE,
    a.WIND_DIRECTION_AVG, b.WIND_DIRECTION_MAX
FROM SORT_WIND_SPEED_AVG a
INNER JOIN SORT_WIND_SPEED_MAX b
    ON a.INPUT_DATE = b.INPUT_DATE
    AND a.PROVINCE_CODE = b.PROVINCE_CODE
    AND a.CITY_CODE = b.CITY_CODE
WHERE a.SORT_ROW = 1
    AND b.SORT_ROW = 1

